name: Publish Release In Parallel

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --verbosity normal
    - name: Test
      run: dotnet test --no-build --verbosity normal 
  templates:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - uses: dotnet/nbgv@master
      name: determine version
      id: version
    - run: echo 'version ${{ steps.version.outputs.SemVer2 }}'
    - name: publish templates
      run: |
        mkdir ./dist
        mkdir ./dist/templates
        cp templates/* ./dist/templates/
    - name: push templates artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: 'templates-${{ steps.version.outputs.SemVer2 }}'
        path: ./dist/templates    
  macos:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - uses: dotnet/nbgv@master
      name: determine version
      id: version
    - run: echo 'version ${{ steps.version.outputs.SemVer2 }}'
    - name: publish macos-arm64
      id: macos-arm64
      run: dotnet publish --runtime osx-arm64 -o ./dist/macos-arm64 mkdoc.csproj
    - name: push macos-arm64 artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: 'mkdoc-macos-arm64-${{ steps.version.outputs.SemVer2 }}'
        path: ./dist/macos-arm64/mkdoc
    - name: publish macos-x64
      id: macos-x64
      run: dotnet publish --runtime osx-x64 -o ./dist/macos-x64 mkdoc.csproj
    - name: push macos-x64 artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: 'mkdoc-macos-x64-${{ steps.version.outputs.SemVer2 }}'
        path: ./dist/macos-x64/mkdoc 
  windows:
    runs-on: win-latest
    needs: test
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - uses: dotnet/nbgv@master
      name: determine version
      id: version
    - run: echo 'version ${{ steps.version.outputs.SemVer2 }}'
    - name: publish win-x64
      id: win-x64
      run: | 
        dotnet publish --runtime win-x64 -o ./dist/win-x64 mkdoc.csproj
    - name: push win-x64 artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: 'mkdoc-win-x64-${{ steps.version.outputs.SemVer2 }}'
        path: ./dist/win-x64/mkdoc.exe
    - name: publish win-arm64
      id: win-arm64
      run: dotnet publish --runtime win-arm64 -o ./dist/win-arm64 mkdoc.csproj
    - name: push win-arm64 artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: 'mkdoc-win-arm64-${{ steps.version.outputs.SemVer2 }}'
        path: ./dist/win-arm64/mkdoc.exe
  linux:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - uses: dotnet/nbgv@master
      name: determine version
      id: version
    - run: echo 'version ${{ steps.version.outputs.SemVer2 }}'
    - name: publish linux-x64
      id: linux-x64
      run: dotnet publish --runtime linux-x64 -o ./dist/linux-x64 mkdoc.csproj
    - name: push linux-x64 artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: 'mkdoc-linux-x64-${{ steps.version.outputs.SemVer2 }}'
        path: ./dist/linux-x64/mkdoc
    - name: publish linux-arm64
      id: linux-arm64
      run: dotnet publish --runtime linux-arm64 -o ./dist/linux-arm64 mkdoc.csproj
    - name: push linux-arm64 artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: 'mkdoc-linux-arm64-${{ steps.version.outputs.SemVer2 }}'
        path: ./dist/linux-arm64/mkdoc
