name: Publish Release

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Test
      run: dotnet test --verbosity normal
    - name: Publish Templates
      run: cp templates/* ./dist/templates/
    - name: Publish Arm MacOS
      run: dotnet publish --runtime osx-arm64 -o ./dist/macos-arm64 mkdoc.csproj
    - name: Upload Arm MacOS mkdoc Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: mkdoc
        path: ./dist/macos-arm64/mkdoc
    - name: Upload templates Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: templates
        path: ./dist/templates
